// prisma/seed.ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Начало сидирования маршрутов TransferRoute...");

  await prisma.transferRoute.deleteMany(); // очищаем перед заполнением

  const routes = [
    {
      slug: "minsk-grodno",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "grodno",
      toNameRu: "Гродно",
      toNameEn: "Grodno",
      toNameZh: "格罗德诺",
      distanceKm: 280,
      durationMin: 200,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 53.6884,
      toLon: 23.8258,
      isPopular: true,
    },
    {
      slug: "minsk-brest",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "brest",
      toNameRu: "Брест",
      toNameEn: "Brest",
      toNameZh: "布列斯特",
      distanceKm: 350,
      durationMin: 240,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 52.0976,
      toLon: 23.6878,
      isPopular: true,
    },
    {
      slug: "minsk-vitebsk",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "vitebsk",
      toNameRu: "Витебск",
      toNameEn: "Vitebsk",
      toNameZh: "维捷布斯克",
      distanceKm: 280,
      durationMin: 210,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 55.1904,
      toLon: 30.2049,
      isPopular: true,
    },
    {
      slug: "minsk-mogilev",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "mogilev",
      toNameRu: "Могилёв",
      toNameEn: "Mogilev",
      toNameZh: "莫吉廖夫",
      distanceKm: 200,
      durationMin: 150,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 53.9007,
      toLon: 30.3314,
      isPopular: true,
    },
    {
      slug: "minsk-gomel",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "gomel",
      toNameRu: "Гомель",
      toNameEn: "Gomel",
      toNameZh: "戈梅利",
      distanceKm: 310,
      durationMin: 220,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 52.4412,
      toLon: 30.9878,
      isPopular: true,
    },
    {
      slug: "minsk-naroch",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "naroch",
      toNameRu: "Нарочь",
      toNameEn: "Naroch",
      toNameZh: "纳罗奇",
      distanceKm: 160,
      durationMin: 130,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 54.907,
      toLon: 26.703,
      isPopular: true,
    },
    {
      slug: "minsk-priozernyy",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "priozernyy",
      toNameRu: "Приозёрный",
      toNameEn: "Priozerny",
      toNameZh: "普里奥泽尔内",
      distanceKm: 155,
      durationMin: 125,
      isPopular: true,
    },
    {
      slug: "minsk-yunost",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "yunost",
      toNameRu: "Юность",
      toNameEn: "Yunost",
      toNameZh: "尤诺斯季",
      distanceKm: 140,
      durationMin: 110,
      isPopular: true,
    },
    {
      slug: "minsk-radon",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "radon",
      toNameRu: "Радон",
      toNameEn: "Radon",
      toNameZh: "拉东",
      distanceKm: 120,
      durationMin: 100,
      isPopular: true,
    },
    {
      slug: "aeroport-minsk-2",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "aeroport-minsk-2",
      toNameRu: "Аэропорт Минск-2",
      toNameEn: "Minsk-2 Airport",
      toNameZh: "明斯克-2机场",
      distanceKm: 45,
      durationMin: 50,
      isAirport: true,
      isPopular: true,
    },
    {
      slug: "minsk-sheremetyevo",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "sheremetyevo",
      toNameRu: "Шереметьево",
      toNameEn: "Sheremetyevo",
      toNameZh: "谢列梅捷沃",
      distanceKm: 720,
      durationMin: 480,
      isInternational: true,
      isPopular: true,
    },
    {
      slug: "minsk-vnukovo",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "vnukovo",
      toNameRu: "Внуково",
      toNameEn: "Vnukovo",
      toNameZh: "伏努科沃",
      distanceKm: 710,
      durationMin: 470,
      isInternational: true,
      isPopular: true,
    },
    {
      slug: "minsk-vilnius",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "vilnius",
      toNameRu: "Вильнюс",
      toNameEn: "Vilnius",
      toNameZh: "维尔纽斯",
      distanceKm: 180,
      durationMin: 140,
      isInternational: true,
      isPopular: true,
    },
    {
      slug: "minsk-warsaw",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "warsaw",
      toNameRu: "Варшава",
      toNameEn: "Warsaw",
      toNameZh: "华沙",
      distanceKm: 550,
      durationMin: 380,
      isInternational: true,
      isPopular: true,
    },
  ];

  for (const route of routes) {
    await prisma.transferRoute.upsert({
      where: { slug: route.slug },
      update: {},
      create: route,
    });
  }

  console.log(`✅ Успешно добавлено ${routes.length} маршрутов!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
