// prisma/seed.ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Начало сидирования маршрутов TransferRoute...");

  await prisma.transferRoute.deleteMany(); // очищаем перед заполнением

  const routes = [
    {
      slug: "minsk-grodno",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "grodno",
      toNameRu: "Гродно",
      toNameEn: "Grodno",
      toNameZh: "格罗德诺",
      distanceKm: 280,
      durationMin: 200,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 53.6884,
      toLon: 23.8258,
      isPopular: true,
      additionalContentRu: `Индивидуальный трансфер Минск — Гродно от SKTransfer — это комфортная и безопасная поездка без стресса. Наш водитель встретит вас с именной табличкой, поможет с багажом и доставит прямо до места назначения. Фиксированная цена, чистый автомобиль премиум-класса и 60 минут бесплатного ожидания гарантированы.`,
      additionalContentEn: `Private transfer from Minsk to Grodno with SKTransfer is a comfortable and stress-free journey. Our driver will meet you with a name plate, assist with luggage, and take you directly to your destination. Fixed price, clean premium-class car, and 60 minutes of free waiting time are guaranteed.`,
      additionalContentZh: `SKTransfer 明斯克至格罗德诺私人接送服务，让您的旅程舒适无忧。我们的司机将手持姓名牌迎接您，帮助处理行李，并直接送您至目的地。固定价格、干净的高级车辆以及60分钟免费等待时间。`,
    },

    {
      slug: "minsk-brest",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "brest",
      toNameRu: "Брест",
      toNameEn: "Brest",
      toNameZh: "布列斯特",
      distanceKm: 350,
      durationMin: 240,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 52.0976,
      toLon: 23.6878,
      isPopular: true,
      additionalContentRu: `Поездка Минск — Брест на комфортном автомобиле с профессиональным водителем. Идеальное решение для тех, кто ценит своё время. Встреча с табличкой, помощь с багажом и приятная атмосфера в салоне гарантированы.`,
      additionalContentEn: `Travel from Minsk to Brest in a comfortable car with a professional driver. The perfect solution for those who value their time. Name plate meeting, luggage assistance, and a pleasant atmosphere are guaranteed.`,
      additionalContentZh: `从明斯克到布列斯特的舒适汽车之旅，配备专业司机。对于珍惜时间的人来说是完美的解决方案。我们提供姓名牌迎接、行李协助以及车内舒适氛围。`,
    },

    {
      slug: "minsk-vitebsk",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "vitebsk",
      toNameRu: "Витебск",
      toNameEn: "Vitebsk",
      toNameZh: "维捷布斯克",
      distanceKm: 280,
      durationMin: 210,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 55.1904,
      toLon: 30.2049,
      isPopular: true,
      additionalContentRu: `Комфортный трансфер Минск — Витебск. Удобный способ добраться в культурную столицу Беларуси с профессиональным водителем.`,
      additionalContentEn: `Comfortable transfer Minsk — Vitebsk. A convenient way to get to the cultural capital of Belarus with a professional driver.`,
      additionalContentZh: `明斯克至维捷布斯克的舒适接送服务。配备专业司机，便捷前往白俄罗斯文化之都。`,
    },

    {
      slug: "minsk-mogilev",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "mogilev",
      toNameRu: "Могилёв",
      toNameEn: "Mogilev",
      toNameZh: "莫吉廖夫",
      distanceKm: 200,
      durationMin: 150,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 53.9007,
      toLon: 30.3314,
      isPopular: true,
      additionalContentRu: `Трансфер Минск — Могилёв на комфортном автомобиле. Быстрая и удобная поездка без пересадок.`,
      additionalContentEn: `Transfer Minsk — Mogilev in a comfortable car. A fast and convenient trip without transfers.`,
      additionalContentZh: `明斯克至莫吉廖夫的舒适汽车接送服务。无需换乘的快速便捷之旅。`,
    },

    {
      slug: "minsk-gomel",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "gomel",
      toNameRu: "Гомель",
      toNameEn: "Gomel",
      toNameZh: "戈梅利",
      distanceKm: 310,
      durationMin: 220,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 52.4412,
      toLon: 30.9878,
      isPopular: true,
      additionalContentRu: `Трансфер Минск — Гомель. Надёжная и комфортная поездка в один из крупнейших городов Беларуси.`,
      additionalContentEn: `Transfer Minsk — Gomel. A reliable and comfortable trip to one of the largest cities in Belarus.`,
      additionalContentZh: `明斯克至戈梅利的接送服务。可靠舒适地前往白俄罗斯最大城市之一。`,
    },

    {
      slug: "minsk-naroch",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "naroch",
      toNameRu: "Нарочь",
      toNameEn: "Naroch",
      toNameZh: "纳罗奇",
      distanceKm: 160,
      durationMin: 130,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 54.907,
      toLon: 26.703,
      isPopular: true,
      additionalContentRu: `Трансфер Минск — Нарочь — популярный маршрут к самому чистому озеру Беларуси. Регулярно возим гостей в санатории и базы отдыха.`,
      additionalContentEn: `Transfer from Minsk to Naroch is a popular route to the cleanest lake in Belarus. We regularly transport guests to sanatoriums and recreation centers.`,
      additionalContentZh: `明斯克至纳罗奇接送服务是前往白俄罗斯最清洁湖泊的热门路线。我们定期接送客人前往疗养院和度假中心。`,
    },

    {
      slug: "minsk-priozernyy",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "priozernyy",
      toNameRu: "Приозёрный",
      toNameEn: "Priozerny",
      toNameZh: "普里奥泽尔内",
      distanceKm: 155,
      durationMin: 125,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 54.85,
      toLon: 26.75,
      isPopular: true,
      additionalContentRu: `Индивидуальный трансфер в санаторий «Приозёрный» на Нарочи. Водитель встретит вас с табличкой и доставит прямо к корпусу.`,
      additionalContentEn: `Private transfer to Priozerny sanatorium on Naroch. The driver will meet you with a name plate and take you directly to the building.`,
      additionalContentZh: `前往纳罗奇「普里奥泽尔内」疗养院的私人接送服务。司机将手持姓名牌迎接您，并直接送您至大楼。`,
    },

    {
      slug: "minsk-yunost",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "yunost",
      toNameRu: "Юность",
      toNameEn: "Yunost",
      toNameZh: "尤诺斯季",
      distanceKm: 140,
      durationMin: 110,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 54.88,
      toLon: 26.72,
      isPopular: true,
      additionalContentRu: `Трансфер в популярный санаторий «Юность» на Нарочи. Комфортная поездка с профессиональным водителем.`,
      additionalContentEn: `Transfer to the popular Yunost sanatorium on Naroch. A comfortable trip with a professional driver.`,
      additionalContentZh: `前往纳罗奇热门疗养院「尤诺斯季」的接送服务。配备专业司机的舒适之旅。`,
    },

    {
      slug: "minsk-radon",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "radon",
      toNameRu: "Радон",
      toNameEn: "Radon",
      toNameZh: "拉东",
      distanceKm: 120,
      durationMin: 100,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 54.32,
      toLon: 26.85,
      isPopular: true,
      additionalContentRu: `Комфортный трансфер в санаторий «Радон». Быстрая и приятная дорога.`,
      additionalContentEn: `Comfortable transfer to Radon sanatorium. A fast and pleasant journey.`,
      additionalContentZh: `前往「拉东」疗养院的舒适接送服务。快速愉快的旅程。`,
    },

    // {
    //   slug: "aeroport-minsk-2",
    //   fromSlug: "minsk",
    //   fromNameRu: "Минск",
    //   fromNameEn: "Minsk",
    //   fromNameZh: "明斯克",
    //   toSlug: "aeroport-minsk-2",
    //   toNameRu: "Аэропорт Минск-2",
    //   toNameEn: "Minsk-2 Airport",
    //   toNameZh: "明斯克-2机场",
    //   distanceKm: 45,
    //   durationMin: 50,
    //   fromLat: 53.9023,
    //   fromLon: 27.5619,
    //   toLat: 53.88,
    //   toLon: 28.03,
    //   isAirport: true,
    //   isPopular: true,
    //   additionalContentRu: `Встреча в аэропорту Минск-2 с табличкой — наш стандарт. 20 минут бесплатного ожидания, помощь с багажом и комфортная поездка.`,
    //   additionalContentEn: `Meeting at Minsk-2 Airport with a name plate is our standard. 20 minutes of free waiting, luggage assistance and a comfortable trip.`,
    //   additionalContentZh: `在明斯克-2机场手持姓名牌迎接是我们的标准服务。包含20分钟免费等待、行李协助和舒适旅程。`,
    // },

    {
      slug: "minsk-sheremetyevo",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "sheremetyevo",
      toNameRu: "Шереметьево",
      toNameEn: "Sheremetyevo",
      toNameZh: "谢列梅捷沃",
      distanceKm: 720,
      durationMin: 480,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 55.972,
      toLon: 37.415,
      isInternational: true,
      isPopular: true,
      additionalContentRu: `Международный трансфер Минск — Шереметьево. Удобный способ добраться в один из крупнейших аэропортов Москвы.`,
      additionalContentEn: `International transfer Minsk — Sheremetyevo. A convenient way to get to one of Moscow's largest airports.`,
      additionalContentZh: `明斯克至谢列梅捷沃国际接送服务。便捷抵达莫斯科最大机场之一的方式。`,
    },

    {
      slug: "minsk-vnukovo",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "vnukovo",
      toNameRu: "Внуково",
      toNameEn: "Vnukovo",
      toNameZh: "伏努科沃",
      distanceKm: 710,
      durationMin: 470,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 55.603,
      toLon: 37.292,
      isInternational: true,
      isPopular: true,
      additionalContentRu: `Трансфер Минск — Внуково. Надёжный способ добраться в аэропорт Внуково без пересадок.`,
      additionalContentEn: `Transfer Minsk — Vnukovo. A reliable way to get to Vnukovo Airport without transfers.`,
      additionalContentZh: `明斯克至伏努科沃接送服务。无需换乘，可靠抵达机场的方式。`,
    },

    {
      slug: "minsk-vilnius",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "vilnius",
      toNameRu: "Вильнюс",
      toNameEn: "Vilnius",
      toNameZh: "维尔纽斯",
      distanceKm: 180,
      durationMin: 140,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 54.6872,
      toLon: 25.2797,
      isInternational: true,
      isPopular: true,
      additionalContentRu: `Комфортный трансфер Минск — Вильнюс. Быстрый способ добраться в столицу Литвы.`,
      additionalContentEn: `Comfortable transfer Minsk — Vilnius. A fast way to get to the capital of Lithuania.`,
      additionalContentZh: `明斯克至维尔纽斯舒适接送服务。快速前往立陶宛首都的方式。`,
    },

    {
      slug: "minsk-warsaw",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "warsaw",
      toNameRu: "Варшава",
      toNameEn: "Warsaw",
      toNameZh: "华沙",
      distanceKm: 550,
      durationMin: 380,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 52.2297,
      toLon: 21.0122,
      isInternational: true,
      isPopular: true,
      additionalContentRu: `Международный трансфер Минск — Варшава. Удобная поездка в столицу Польши.`,
      additionalContentEn: `International transfer Minsk — Warsaw. A comfortable trip to the capital of Poland.`,
      additionalContentZh: `明斯克至华沙国际接送服务。舒适前往波兰首都的旅程。`,
    },

    {
      slug: "minsk-polotsk",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "polotsk",
      toNameRu: "Полоцк",
      toNameEn: "Polotsk",
      toNameZh: "波洛茨克",
      distanceKm: 220,
      durationMin: 170,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 55.4879,
      toLon: 28.8049,
      isPopular: false,
      additionalContentRu: `Трансфер в древний Полоцк — один из старейших городов Беларуси.`,
      additionalContentEn: `Transfer to the ancient city of Polotsk, one of the oldest cities in Belarus.`,
      additionalContentZh: `前往白俄罗斯最古老城市之一的波洛茨克的接送服务。`,
    },

    {
      slug: "minsk-baranovichi",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "baranovichi",
      toNameRu: "Барановичи",
      toNameEn: "Baranovichi",
      toNameZh: "巴拉诺维奇",
      distanceKm: 140,
      durationMin: 110,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 53.1325,
      toLon: 26.0325,
      isPopular: false,
      additionalContentRu: `Комфортный трансфер Минск — Барановичи по отличной трассе.`,
      additionalContentEn: `Comfortable transfer Minsk — Baranovichi on an excellent highway.`,
      additionalContentZh: `明斯克至巴拉诺维奇的舒适接送服务，在优质公路上行驶。`,
    },

    {
      slug: "minsk-lida",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "lida",
      toNameRu: "Лида",
      toNameEn: "Lida",
      toNameZh: "利达",
      distanceKm: 180,
      durationMin: 140,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 53.888,
      toLon: 25.299,
      isPopular: false,
      additionalContentRu: `Трансфер в Лиду — город с богатой историей и знаменитым замком.`,
      additionalContentEn: `Transfer to Lida — a city with rich history and a famous castle.`,
      additionalContentZh: `前往拥有丰富历史和著名城堡的利达的接送服务。`,
    },

    {
      slug: "minsk-soligorsk",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "soligorsk",
      toNameRu: "Солигорск",
      toNameEn: "Soligorsk",
      toNameZh: "索利戈尔斯克",
      distanceKm: 130,
      durationMin: 100,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 52.79,
      toLon: 27.54,
      isPopular: false,
      additionalContentRu: `Трансфер Минск — Солигорск. Популярный маршрут для деловых поездок.`,
      additionalContentEn: `Transfer Minsk — Soligorsk. A popular route for business trips.`,
      additionalContentZh: `明斯克至索利戈尔斯克的接送服务。适合商务出行的热门路线。`,
    },

    {
      slug: "minsk-bobruysk",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "bobruysk",
      toNameRu: "Бобруйск",
      toNameEn: "Bobruysk",
      toNameZh: "博布鲁伊斯克",
      distanceKm: 145,
      durationMin: 120,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 53.15,
      toLon: 29.23,
      isPopular: false,
      additionalContentRu: `Трансфер в Бобруйск — город с богатой историей и крепостью.`,
      additionalContentEn: `Transfer to Bobruysk — a city with rich history and a fortress.`,
      additionalContentZh: `前往拥有丰富历史和要塞的博布鲁伊斯克的接送服务。`,
    },

    {
      slug: "minsk-orsha",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "orsha",
      toNameRu: "Орша",
      toNameEn: "Orsha",
      toNameZh: "奥尔沙",
      distanceKm: 210,
      durationMin: 160,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 54.51,
      toLon: 30.42,
      isPopular: false,
      additionalContentRu: `Трансфер Минск — Орша. Удобная поездка в один из древних городов Беларуси.`,
      additionalContentEn: `Transfer Minsk — Orsha. A convenient trip to one of the ancient cities of Belarus.`,
      additionalContentZh: `明斯克至奥尔沙的接送服务。便捷前往白俄罗斯古老城市之一。`,
    },

    {
      slug: "minsk-mozyr",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "mozyr",
      toNameRu: "Мозырь",
      toNameEn: "Mozyr",
      toNameZh: "莫济里",
      distanceKm: 280,
      durationMin: 210,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 52.05,
      toLon: 29.23,
      isPopular: false,
      additionalContentRu: `Трансфер в Мозырь — город на Припяти с красивой природой.`,
      additionalContentEn: `Transfer to Mozyr — a city on the Pripyat River with beautiful nature.`,
      additionalContentZh: `前往位于普里皮亚季河畔、拥有美丽自然风光的莫济里的接送服务。`,
    },

    {
      slug: "minsk-pinsk",
      fromSlug: "minsk",
      fromNameRu: "Минск",
      fromNameEn: "Minsk",
      fromNameZh: "明斯克",
      toSlug: "pinsk",
      toNameRu: "Пинск",
      toNameEn: "Pinsk",
      toNameZh: "平斯克",
      distanceKm: 300,
      durationMin: 230,
      fromLat: 53.9023,
      fromLon: 27.5619,
      toLat: 52.11,
      toLon: 26.09,
      isPopular: false,
      additionalContentRu: `Трансфер Минск — Пинск. Комфортная поездка в один из самых красивых городов Полесья.`,
      additionalContentEn: `Transfer Minsk — Pinsk. A comfortable trip to one of the most beautiful cities in Polesie.`,
      additionalContentZh: `明斯克至平斯克的舒适接送服务。前往波列西耶最美丽城市之一的愉快之旅。`,
    },
  ];

  for (const route of routes) {
    await prisma.transferRoute.upsert({
      where: { slug: route.slug },
      update: {},
      create: route,
    });
  }

  console.log(
    `✅ Успешно добавлено ${routes.length} маршрутов с координатами и дополнительным контентом!`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
